<?php
/**
 * Title: Modélisation 3D
 * Slug: modelisation-3d
 * Categories: 
 */
?>
<!-- wp:group {"style":{"spacing":{"padding":{"right":"var:preset|spacing|70","left":"var:preset|spacing|70","top":"var:preset|spacing|70","bottom":"var:preset|spacing|70"}}},"backgroundColor":"custom-transparent","layout":{"type":"constrained"}} -->
<div class="wp-block-group has-custom-transparent-background-color has-background" style="padding-top:var(--wp--preset--spacing--70);padding-right:var(--wp--preset--spacing--70);padding-bottom:var(--wp--preset--spacing--70);padding-left:var(--wp--preset--spacing--70)"><!-- wp:heading {"fontSize":"x-large"} -->
<h2 class="wp-block-heading has-x-large-font-size"><?php /* Translators: 1. is the start of a 'strong' HTML element, 2. is the end of a 'strong' HTML element */ 
echo sprintf( esc_html__( '%1$sModélisation 3D%2$s', '' ), '<strong>', '</strong>' ); ?></h2>
<!-- /wp:heading -->

<!-- wp:group {"style":{"border":{"radius":{"topLeft":"0px","topRight":"0px","bottomLeft":"0px","bottomRight":"0px"},"width":"0px","style":"none"}},"backgroundColor":"custom-transparent","layout":{"type":"grid"}} -->
<div class="wp-block-group has-custom-transparent-background-color has-background" style="border-style:none;border-width:0px;border-top-left-radius:0px;border-top-right-radius:0px;border-bottom-left-radius:0px;border-bottom-right-radius:0px"><!-- wp:b3dviewer/modelviewer {"uniqueId":"b3dviewer5af4f903","model":{"skyboxImage":null,"environmentImage":null,"arEnabled":false,"arPlacement":"floor","arMode":"quick-look","arScale":"fixed","modelUrl":"https://mmi.unilim.fr/~thierry18/laboutiquezelda/wp-content/uploads/2026/04/Triforce.glb"},"lazyLoad":false,"mouseControl":false,"progressBar":false,"styles":{"width":{"desktop":"300px","tablet":"300px","mobile":"300px"},"height":{"desktop":"300px","tablet":"300px","mobile":"300px"},"bgColor":"transparent","progressBarColor":"#666","thumbSize":"300px"}} /-->

<!-- wp:b3dviewer/modelviewer {"uniqueId":"b3dviewer9332889f","model":{"skyboxImage":null,"environmentImage":null,"arEnabled":false,"arPlacement":"floor","arMode":"quick-look","arScale":"fixed","modelUrl":"https://mmi.unilim.fr/~thierry18/laboutiquezelda/wp-content/uploads/2026/04/Epee-de-legende.glb"},"lazyLoad":false,"mouseControl":false,"progressBar":false,"styles":{"width":{"desktop":"300px","tablet":"300px","mobile":"300px"},"height":{"desktop":"300px","tablet":"300px","mobile":"300px"},"bgColor":"transparent","progressBarColor":"#666","thumbSize":"300px"}} /-->

<!-- wp:b3dviewer/modelviewer {"uniqueId":"b3dviewer5f1d8727","model":{"skyboxImage":null,"environmentImage":null,"arEnabled":false,"arPlacement":"floor","arMode":"quick-look","arScale":"fixed","modelUrl":"https://mmi.unilim.fr/~thierry18/laboutiquezelda/wp-content/uploads/2026/04/Statuette-de-Dragon.glb"},"lazyLoad":false,"mouseControl":false,"progressBar":false,"styles":{"width":{"desktop":"300px","tablet":"300px","mobile":"300px"},"height":{"desktop":"300px","tablet":"300px","mobile":"300px"},"bgColor":"transparent","progressBarColor":"#666","thumbSize":"300px"}} /-->

<!-- wp:b3dviewer/modelviewer {"uniqueId":"b3dviewer9a0e69b4","model":{"skyboxImage":null,"environmentImage":null,"arEnabled":false,"arPlacement":"floor","arMode":"quick-look","arScale":"fixed","modelUrl":"https://mmi.unilim.fr/~thierry18/laboutiquezelda/wp-content/uploads/2026/04/Sculpture-Doree.glb"},"lazyLoad":false,"mouseControl":false,"progressBar":false,"styles":{"width":{"desktop":"300px","tablet":"300px","mobile":"300px"},"height":{"desktop":"300px","tablet":"300px","mobile":"300px"},"bgColor":"transparent","progressBarColor":"#666","thumbSize":"300px"}} /-->

<!-- wp:b3dviewer/modelviewer {"uniqueId":"b3dviewer4214b9ae","model":{"skyboxImage":null,"environmentImage":null,"arEnabled":false,"arPlacement":"floor","arMode":"quick-look","arScale":"fixed","modelUrl":"https://mmi.unilim.fr/~thierry18/laboutiquezelda/wp-content/uploads/2026/04/Protectine.glb"},"lazyLoad":false,"mouseControl":false,"progressBar":false,"styles":{"width":{"desktop":"300px","tablet":"300px","mobile":"300px"},"height":{"desktop":"300px","tablet":"300px","mobile":"300px"},"bgColor":"transparent","progressBarColor":"#666","thumbSize":"300px"}} /-->

<!-- wp:b3dviewer/modelviewer {"uniqueId":"b3dviewer1c7484a7","model":{"skyboxImage":null,"environmentImage":null,"arEnabled":false,"arPlacement":"floor","arMode":"quick-look","arScale":"fixed","modelUrl":"https://mmi.unilim.fr/~thierry18/laboutiquezelda/wp-content/uploads/2026/04/Potion-de-soin.glb"},"lazyLoad":false,"mouseControl":false,"progressBar":false,"styles":{"width":{"desktop":"300px","tablet":"300px","mobile":"300px"},"height":{"desktop":"300px","tablet":"300px","mobile":"300px"},"bgColor":"transparent","progressBarColor":"#666","thumbSize":"300px"}} /-->

<!-- wp:b3dviewer/modelviewer {"uniqueId":"b3dviewerf9396bb7","model":{"skyboxImage":null,"environmentImage":null,"arEnabled":false,"arPlacement":"floor","arMode":"quick-look","arScale":"fixed","modelUrl":"https://mmi.unilim.fr/~thierry18/laboutiquezelda/wp-content/uploads/2026/04/Potion-d-oxygene.glb"},"lazyLoad":false,"mouseControl":false,"progressBar":false,"styles":{"width":{"desktop":"300px","tablet":"300px","mobile":"300px"},"height":{"desktop":"300px","tablet":"300px","mobile":"300px"},"bgColor":"transparent","progressBarColor":"#666","thumbSize":"300px"}} /-->

<!-- wp:b3dviewer/modelviewer {"uniqueId":"b3dviewer5da2c813","model":{"skyboxImage":null,"environmentImage":null,"arEnabled":false,"arPlacement":"floor","arMode":"quick-look","arScale":"fixed","modelUrl":"https://mmi.unilim.fr/~thierry18/laboutiquezelda/wp-content/uploads/2026/04/Polypotion.glb","initialView":null,"ext":"glb"},"O3DVSettings":{"isFullscreen":true,"isPagination":false,"isNavigation":false,"camera":null,"mouseControl":false,"showEdge":false,"zoom":true},"lazyLoad":false,"mouseControl":false,"progressBar":false,"styles":{"width":{"desktop":"300px","tablet":"300px","mobile":"300px"},"height":{"desktop":"300px","tablet":"300px","mobile":"300px"},"bgColor":"transparent","progressBarColor":"#666","thumbSize":"300px"}} /-->

<!-- wp:b3dviewer/modelviewer {"uniqueId":"b3dviewercbadb801","model":{"skyboxImage":null,"environmentImage":null,"arEnabled":false,"arPlacement":"floor","arMode":"quick-look","arScale":"fixed","modelUrl":"https://mmi.unilim.fr/~thierry18/laboutiquezelda/wp-content/uploads/2026/04/Endurol.glb"},"lazyLoad":false,"mouseControl":false,"progressBar":false,"styles":{"width":{"desktop":"300px","tablet":"300px","mobile":"300px"},"height":{"desktop":"300px","tablet":"300px","mobile":"300px"},"bgColor":"transparent","progressBarColor":"#666","thumbSize":"300px"}} /-->

<!-- wp:b3dviewer/modelviewer {"uniqueId":"b3dviewer99f6f229","model":{"skyboxImage":null,"environmentImage":null,"arEnabled":false,"arPlacement":"floor","arMode":"quick-look","arScale":"fixed","modelUrl":"https://mmi.unilim.fr/~thierry18/laboutiquezelda/wp-content/uploads/2026/04/Fee.glb"},"lazyLoad":false,"mouseControl":false,"progressBar":false,"styles":{"width":{"desktop":"300px","tablet":"300px","mobile":"300px"},"height":{"desktop":"300px","tablet":"300px","mobile":"300px"},"bgColor":"transparent","progressBarColor":"#666","thumbSize":"300px"}} /-->

<!-- wp:b3dviewer/modelviewer {"uniqueId":"b3dviewer7260ad7e","model":{"skyboxImage":null,"environmentImage":null,"arEnabled":false,"arPlacement":"floor","arMode":"quick-look","arScale":"fixed","modelUrl":"https://mmi.unilim.fr/~thierry18/laboutiquezelda/wp-content/uploads/2026/04/Medaille-Rubis.glb"},"lazyLoad":false,"mouseControl":false,"progressBar":false,"styles":{"width":{"desktop":"300px","tablet":"300px","mobile":"300px"},"height":{"desktop":"300px","tablet":"300px","mobile":"300px"},"bgColor":"transparent","progressBarColor":"#666","thumbSize":"300px"}} /-->

<!-- wp:b3dviewer/modelviewer {"uniqueId":"b3dviewer17ca72df","model":{"skyboxImage":null,"environmentImage":null,"arEnabled":false,"arPlacement":"floor","arMode":"quick-look","arScale":"fixed","modelUrl":"https://mmi.unilim.fr/~thierry18/laboutiquezelda/wp-content/uploads/2026/04/Medaille-Coeur.glb"},"lazyLoad":false,"mouseControl":false,"progressBar":false,"styles":{"width":{"desktop":"300px","tablet":"300px","mobile":"300px"},"height":{"desktop":"300px","tablet":"300px","mobile":"300px"},"bgColor":"transparent","progressBarColor":"#666","thumbSize":"300px"}} /-->

<!-- wp:b3dviewer/modelviewer {"uniqueId":"b3dviewerb5f1fcae","model":{"skyboxImage":null,"environmentImage":null,"arEnabled":false,"arPlacement":"floor","arMode":"quick-look","arScale":"fixed","modelUrl":"https://mmi.unilim.fr/~thierry18/laboutiquezelda/wp-content/uploads/2026/04/Bouclier-en-Bois.glb"},"lazyLoad":false,"mouseControl":false,"progressBar":false,"styles":{"width":{"desktop":"300px","tablet":"300px","mobile":"300px"},"height":{"desktop":"300px","tablet":"300px","mobile":"300px"},"bgColor":"transparent","progressBarColor":"#666","thumbSize":"300px"}} /-->

<!-- wp:b3dviewer/modelviewer {"uniqueId":"b3dviewerafa98c55","model":{"skyboxImage":null,"environmentImage":null,"arEnabled":false,"arPlacement":"floor","arMode":"quick-look","arScale":"fixed","modelUrl":"https://mmi.unilim.fr/~thierry18/laboutiquezelda/wp-content/uploads/2026/04/Rubis-Vert.glb"},"mouseControl":false,"styles":{"width":{"desktop":"300px","tablet":"100%","mobile":"100%"},"height":{"desktop":"300px","tablet":"300px","mobile":"300px"},"bgColor":"transparent","progressBarColor":"#666","thumbSize":"90px"}} /-->

<!-- wp:b3dviewer/modelviewer {"uniqueId":"b3dvieweree17bedb","model":{"skyboxImage":null,"environmentImage":null,"arEnabled":false,"arPlacement":"floor","arMode":"quick-look","arScale":"fixed","modelUrl":"https://mmi.unilim.fr/~thierry18/laboutiquezelda/wp-content/uploads/2026/04/Rubis-Rouge.glb"},"mouseControl":false,"styles":{"width":{"desktop":"300px","tablet":"100%","mobile":"100%"},"height":{"desktop":"300px","tablet":"300px","mobile":"300px"},"bgColor":"transparent","progressBarColor":"#666","thumbSize":"90px"}} /-->

<!-- wp:b3dviewer/modelviewer {"uniqueId":"b3dviewerb04d248d","model":{"skyboxImage":null,"environmentImage":null,"arEnabled":false,"arPlacement":"floor","arMode":"quick-look","arScale":"fixed","modelUrl":"https://mmi.unilim.fr/~thierry18/laboutiquezelda/wp-content/uploads/2026/04/Rubis-Bleu.glb"},"mouseControl":false,"styles":{"width":{"desktop":"300%","tablet":"100%","mobile":"100%"},"height":{"desktop":"300px","tablet":"300px","mobile":"300px"},"bgColor":"transparent","progressBarColor":"#666","thumbSize":"90px"}} /-->

<!-- wp:b3dviewer/modelviewer {"uniqueId":"b3dviewer8337f4cc","model":{"skyboxImage":null,"environmentImage":null,"arEnabled":false,"arPlacement":"floor","arMode":"quick-look","arScale":"fixed","modelUrl":"https://mmi.unilim.fr/~thierry18/laboutiquezelda/wp-content/uploads/2026/04/Rubis-Argente.glb"},"mouseControl":false,"styles":{"width":{"desktop":"300px","tablet":"100%","mobile":"100%"},"height":{"desktop":"300px","tablet":"300px","mobile":"300px"},"bgColor":"transparent","progressBarColor":"#666","thumbSize":"90px"}} /-->

<!-- wp:b3dviewer/modelviewer {"uniqueId":"b3dviewerdf97fcf1","model":{"skyboxImage":null,"environmentImage":null,"arEnabled":false,"arPlacement":"floor","arMode":"quick-look","arScale":"fixed","modelUrl":"https://mmi.unilim.fr/~thierry18/laboutiquezelda/wp-content/uploads/2026/04/Rubis-Dore.glb"},"mouseControl":false,"styles":{"width":{"desktop":"300%","tablet":"100%","mobile":"100%"},"height":{"desktop":"300px","tablet":"300px","mobile":"300px"},"bgColor":"transparent","progressBarColor":"#666","thumbSize":"90px"}} /--></div>
<!-- /wp:group --></div>
<!-- /wp:group -->